#!/bin/bash

extract_branch_name() {
    local session_name="$1"
    local branch_name=$(echo "$session_name" | grep -oP '@@\K[^@]+')
    echo "$branch_name"
}

tmux select-pane -t '{bottom-right}'

session_name=$(tmuxp ls | fzf)

if [[ -n "$session_name" ]]; then
    tmuxp load -y "$session_name"

    # branch_name=$(extract_branch_name "$session_name")
    # if [[ -n "$branch_name" ]]; then
    #     cd "$(git rev-parse --show-toplevel)"
    #     git checkout "$branch_name"
    # fi
fi
